RESCACHED.CONF(5)
=================
:doctype: manpage
:man source: rescached.cfg
:man version: 2018.08.26
:man manual: rescached.cfg


== NAME

rescached.cfg - Configuration for rescached service


== SYNOPSIS

/etc/rescached/rescached.cfg


== DESCRIPTION

These file configure the behaviour of *rescached*(1) service.
In those file you can see some comment for any option and some possible value.
This section will explain more about each option and how they effect
+rescached+.

The configuration is using INI format where each options is grouped by header
in square bracket:

* +[rescached]+
* +[log]+


== OPTIONS

=== +[rescached]+

This group of options contain the main configuration.

[[server.parent]]
==== +server.parent+

Format:: IP-ADDRESS:PORT, IP-ADDRESS:PORT, ...
Default::
* Address: 8.8.8.8 and 8.8.4.4
* Port: 53
Description:: List of parent DNS servers, separated by commas.
When +rescached+ receive a query from client and when it does
not have a cached address of query, it will pass the query to those parent
server.
+rescached+ use a Google DNS public server as a default parent address if not set.
The reason for this is that Google DNS public server use a simple and small
size of response/answer.
Please, do not use OpenDNS server.
If certain host-name not found (i.e. typo in host-name), OpenDNS will reply
with its own address, instead of replying with empty answer.
This will make +rescached+ caching a false data.
To check if your parent server reply the unknown host-name with no answer, use
*resolver*(1) tool.

[[server.parent.connection]]
==== +server.parent.connection+

Format:: String ("udp" or "tcp", without quotes)
Default:: udp
Description:: Type of protocol that will be used to send request to
+server.parent+.
When +rescached+ receive query from client it will forward the query to the
+server.parent+ using default protocol (UDP).
In case UDP is blocked, you can set this variable to "tcp".

[[server.parent.allow_insecure]]
==== +server.parent.allow_insecure+

Format:: true | false
Default:: false
Description:: If its true, allow insecure TLS connection
to parent server when connection is "doh".

[[server.listen]]
==== +server.listen+

Format:: 	<IP-ADDRESS>:<PORT>
Default:: 	127.0.0.1:53
Description:: 	Address in local network where +rescached+ will listening for
query from client.
If you want rescached to serve a query from another host in your local
network, change this value to +0.0.0.0:53+.

[[server.timeout]]
==== +server.timeout+

Format:: 	Number
Default:: 	6
Description:: 	This option set the server read and write timeout value.

[[cache.prune_delay]]
==== +cache.prune_delay+

Format:: 	Duration
Default:: 	5m
Description::   Every N seconds/minutes/hours, rescached will traverse all
caches and remove response that has not been accessed less than
+cache.threshold+.

[[cache.threshold]]
==== +cache.threshold+

Format:: 	Duration
Default:: 	1h
Description:: 	The duration when the cache will be considered expired.

[[dir.hosts]]
==== +dir.hosts+

Format:: string
Default:: /etc/rescached/hosts.d
Description:: Path to hosts directory.
If set, rescached will load all hosts formatted files inside the directory.
If its empty or unset, it will not loading hosts files even in default
location.

[[dir.zone]]
==== +dir.zone+

Format:: string
Default:: /etc/rescached/zone.d
Description::  Path to zone directory.
If set, rescached will load all master files inside directory.
If its empty or unset, it will not loading zone file even in default
location.

[[file.pid]]
==== +file.pid+

Format:: /any/path/to/file
Default:: rescached.pid (in current directory)
Description:: When +rescached+ started, it will create this file as a mediator
to any system service.
Content of this file is the process ID (PID) of +rescached+ in system.
If not set then the default name will be used, and it will be saved in current
directory where user running +rescached+.

[[file.resolvconf]]
==== +file.resolvconf+

Format:: /any/path/to/file
Default:: /etc/rescached/resolv.conf
Description:: A path to dynamically generated resolv.conf (5) by
resolvconf (8).  If set, the nameserver values in referenced file will
replace "server.parent" value and "server.parent" will become a fallback in
case the referenced file being deleted or can't be parsed.

To use this config, you must set either "dnsmasq_resolv", "pdnsd_resolv", or
"unbound_conf" in "/etc/resolvconf.conf" to point to
"/etc/rescached/resolv.conf".

For example,
----
resolv_conf=/etc/resolv.conf
name_servers=127.0.0.1
dnsmasq_resolv=/etc/rescached/resolv.conf
#pdnsd_resolv=/etc/rescached/resolv.conf
#unbound_conf=/etc/rescached/resolv.conf
----


[[debug]]
==== +debug+

Value::
0::: log nothing.
1::: log startup, request, response, caches, and exit status.
Format:: 	Number (0 or 1).
Default:: 	0
Description:: 	This option only used by developer for debugging program or if
user want to monitor what kind of traffic goes out, set this option to 1.


== EXAMPLE

Simple rescached configuration using dnscrypt-proxy that listen on port 54 as
parent resolver, with prune delay set to 60 seconds and threshold also to 60
seconds.

..............................................................................
[rescached]
server.parent=127.0.0.1:54
cache.prune_delay=60s
cache.threshold=60s
..............................................................................

Save the above script into +rescached.cfg+ and run it,

	$ sudo rescached -f rescached.cfg


== AUTHOR

+rescached+ is developed by M. Shulhan (ms@kilabit.info).


== LICENSE

Copyright 2018, M. Shulhan (ms@kilabit.info).
All rights reserved.

Use of this source code is governed by a BSD-style license that can be found
in the LICENSE file.


== SEE ALSO

*rescached*(1)
