// SPDX-FileCopyrightText: 2020 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
= RESOLVER(1)
:doctype: manpage
:man source: resolver
:man version: 2022.04.15
:man manual: resolver


== NAME

resolver - command line interface for DNS and rescached server.


== SYNOPSIS

resolver [-insecure] [-ns nameserver] [-server] <command> [args...]


== DESCRIPTION

resolver is a tool to resolve hostname to IP address or to query services
on hostname by type (MX, SOA, TXT, etc.) using standard DNS protocol with UDP,
DNS over TLS (DoT), or DNS over HTTPS (DoH).


== OPTIONS

`-insecure`::
+
--
Ignore invalid server certificate when querying DoT, DoH, or rescached server.
--

`-ns <nameserver>`::
+
--
This option define the parent DNS server where the resolver send the query.
Default to one of "nameserver" in `/etc/resolv.conf`.

The nameserver is defined in the following format,

		("udp"/"tcp"/"https") "://" (domain / ip-address) [":" port]

Examples,

* udp://194.233.68.184:53 for querying with UDP,
* tcp://194.233.68.184:53 for querying with TCP,
* https://194.233.68.184:853 for querying with DNS over TLS (DoT), and
* https://kilabit.info/dns-query for querying with DNS over HTTPS (DoH).
--

`-server <rescached-URL>`::
+
--
Set the rescached HTTP server where commands will send.
The rescached-URL use HTTP scheme:

	("http" / "https") "://" (domain / ip-address) [":" port]

Default to "https://127.0.0.1:5380" if its empty.
--

==  COMMANDS

query <domain / ip-address> [type] [class]::
+
--
Query the domain or IP address with optional type and/or class.

Unless the option "-ns" is given, the query command will use the
nameserver defined in the system resolv.conf file.

The "type" parameter define DNS record type to be queried.
List of valid types,

* A       (1) - a host Address (default)
* NS      (2) - an authoritative Name Server
* CNAME   (5) - the Canonical NAME for an alias
* SOA     (6) - marks the Start of a zone of Authority
* MB      (7) - a MailBox domain name
* MG      (8) - a Mail Group member
* MR      (9) - a Mail Rename domain name
* NULL   (10) - a null resource record
* WKS    (11) - a Well Known Service description
* PTR    (12) - a domain name PoinTeR
* HINFO  (13) - Host INFOrmation
* MINFO  (14) - mailbox or mail list information
* MX     (15) - Mail Exchange
* TXT    (16) - TeXT strings
* AAAA   (28) - a host address in IPv6
* SRV    (33) -  a SerViCe record

The "class" parameter is optional, its either IN (default), CS, or HS.
--

block.d disable <name>::
+
--
Disable specific hosts on block.d.
--

block.d enable <name>::
+
--
Enable specific hosts on block.d.
--

block.d update <name>::
+
--
Fetch the latest hosts file from remote block.d URL defined by
its name.
On success, the hosts file will be updated and the server will be
restarted.
--


caches::
+
--
Fetch and print all caches from rescached server.
--


caches search <string>::
+
--
Search the domain name in rescached caches.
This command can also be used to inspect each DNS message on the caches.
--

caches remove <string>::
+
--
Remove the domain name from rescached caches.
If the parameter is "all", it will remove all caches.
--

env::
+
--
Fetch the current server environment and print it as JSON format to stdout.
--

env update <path-to-file / "-">::
+
--
Update the server environment from JSON formatted file.
If the argument is "-", the new environment is read from stdin.
If the environment is valid, the server will be restarted.
--

hosts.d create <name>::
+
--
Create new hosts file inside the hosts.d directory with specific file
name.
--

hosts.d delete <name>::
+
--
Delete hosts file inside the hosts.d directory by file name.
--

hosts.d get <name>::
+
--
Get the content of hosts file inside the hosts.d directory by file name.
--


== EXIT STATUS

Upon exit and success +resolver+ will return 0, or 1 otherwise.


== EXAMPLES

Query the IPv4 address for kilabit.info,

	$ resolver query kilabit.info

Query the mail exchange (MX) for domain kilabit.info,

	$ resolver query kilabit.info MX

Query the IPv4 address for kilabit.info using 127.0.0.1 at port 53 as
name server,

	$ resolver -ns=udp://127.0.0.1:53 query kilabit.info

Query the IPv4 address of domain name "kilabit.info" using DNS over TLS at
name server 194.233.68.184,

	$ resolver -insecure -ns=https://194.233.68.184 query kilabit.info

Query the IPv4 records of domain name "kilabit.info" using DNS over HTTPS on
name server kilabit.info,

	$ resolver -ns=https://kilabit.info/dns-query query kilabit.info

Inspect the rescached's caches on server at http://127.0.0.1:5380,

	$ resolver -server=http://127.0.0.1:5380 caches

Search caches that contains "bit" on the domain name,

	$ resolver caches search bit

Remove caches that contains domain name "kilabit.info",

	$ resolver caches remove kilabit.info

Remove all caches in the server,

	$ resolver caches remove all

Fetch and print current server environment,

	$ resolver env

Update the server environment from JSON file in /tmp/env.json,

	$ resolver env update /tmp/env.json

Update the server environment by reading JSON from standard input,

	$ cat /tmp/env.json | resolver env update -

Create new hosts file named "myhosts" inside the hosts.d directory,

	$ resolver hosts.d create myhosts
	OK

Delete hosts file named "myhosts" inside the hosts.d directory,

	$ resolver hosts.d delete myhosts
	OK

Get the content of hosts file named "myhosts" inside the hosts.d directory,

	$ resolver hosts.d get myhosts
	[
	  {
	    "Value": "127.0.0.1",
	    "Name": "localhost",
	    "Type": 1,
	    "Class": 1,
	    "TTL": 604800
	  },
	  {
	    "Value": "::1",
	    "Name": "localhost",
	    "Type": 28,
	    "Class": 1,
	    "TTL": 604800
	  }
	]


== AUTHOR

This software is developed by M. Shulhan (ms@kilabit.info).


== LICENSE

Copyright 2018, M. Shulhan (ms@kilabit.info).
All rights reserved.

Use of this source code is governed by a GPL 3.0 license that can be
found in the COPYING file.


== LINKS

Source code repository: https://github.com/shuLhan/rescached-go


== SEE ALSO

*rescached*(1), *rescached.cfg*(5)
